// Server public key (PEM format)
const SERVER_PUBLIC_KEY = `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQE1LYRHL+5vRJk+Dz1AJyx
XVz2G0ya1XiWxoPLAo5mFwYMXXsiW4Ne5hKwy6UVnBw6jbUy4XvFYdypn/cSHcOy
wpSldDqKTstekphUyAALYgecuwURHqpY0slxEcYVNS2t8rsFH+E0wf4obyIKdhz6
65HRR45xRW+3ewt+GWURJDcnmli0O8KSWSDTNR8MHKywfxOVYMaG1h4Jy9pv6q7Z
lSYBDLvqh5PQkPs7nTCqs2uJD+N/kMfd5+AIJ85PhKiWeqp7YPLeLFhoZKAnVHHv
L+d9mLca248mvlpG4PHIRHb2LIDQbBG8mrT/uyGPQnsmYRMxHDanhJ2xwoK/mwhC
EwIDAQAB
-----END PUBLIC KEY-----`;

export default SERVER_PUBLIC_KEY;
